default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: shortstaq_development

test:
  <<: *default
  database: shortstaq_test

production:
  <<: *default
  database: shortstaq_production
  username: awesome_shortstaq
  password: <%= ENV['AWESOME_BLOG_DATABASE_PASSWORD'] %>
