# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23fb47a784239c3096532dad6d43765c1cd4b536dff8ac4a2dc55c1503332ac593316bc50508f74c89aa72dd363dd7ffd7c08b8d242903afbbf7ee81debe4016

test:
  secret_key_base: 9aca51db1dd48ab742852575ddb2f7762f414b7ba0d4182d132b48bc75cd4de35411d657d7a607abc0c7c9564fdbce3c31763aea15b4705c6aa8358462604d26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
